name: trackfit_flutter
description: A premium fitness, water, meals, and workout tracker with dual database support.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  sqflite: ^2.3.3+1
  postgres: ^3.2.1
  fl_chart: ^0.68.0
  google_fonts: 6.2.1
  path_provider: ^2.1.4
  intl: ^0.19.0
  path: any
  sqflite_common_ffi: any
  sqlite3_flutter_libs: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/exercises.json
    - assets/foods.json
    - assets/logo.svg
